# Generated by Django 2.0.7 on 2018-08-13 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('endereco', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='produtos',
            name='fornecedor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='produtos_api.Fornecedores'),
            preserve_default=False,
        ),
    ]
