# Generated by Django 2.0.7 on 2018-08-13 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos_api', '0002_auto_20180813_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='fornecedor',
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='cnpj',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='produtos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produtos_api.Produtos'),
            preserve_default=False,
        ),
    ]
