# Generated by Django 2.0.7 on 2018-08-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos_api', '0005_auto_20180813_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='produtos',
            field=models.ManyToManyField(blank=True, to='produtos_api.Produtos'),
        ),
    ]
