# Generated by Django 2.0.7 on 2018-08-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos_api', '0006_auto_20180814_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='produtos',
            field=models.ManyToManyField(blank=True, default='', to='produtos_api.Produtos'),
        ),
    ]
